export const fluffImage = new Image();
fluffImage.src =
  'data:image/gif;base64,R0lGODlhGAAYALMIAHyHjZqmrF5nbbPAxczZ3kBITg8PD////////wAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAAgALAAAAAAYABgAAARYEMlJq7046827/2CIGIY4GUdJkh+qHsQAlNt6FOggkLOWB4HdYDWiXVABQyEw0wF6vuFoydwZMwYCjSQQQGupEQGwY16xyeLrjD27TJK3Kcv2EOH4vN4UAQA7';
