export const redHerbImage = new Image();
redHerbImage.src =
  'data:image/gif;base64,R0lGODlhGAAYALMMAFMTAJdfP0MAB2sLG69bT8tkb//et1cbG4I3N/uQo7VDVQ8PD////wAAAAAAAAAAACH5BAEAAAwALAAAAAAYABgAAASEkMlJq704a7n6zkuCLN8VJkBpLUZCri/GJkHMLYq9tnYXDDmQQVGILQ4ihUuoGHESSEQiaEoYCgfSIiCainSTUAHwOilaTTCnoEitW8O0eoEtHwoGgmKvyJoObgxHBVNNCE4ydlcFhwd+JQdXfAoCalVshyOWfwgHlZuJHaAqpKWmp6cRADs=';
