export const shellImage = new Image();
shellImage.src =
  "data:image/gif;base64,R0lGODlhGAAYALMIAPvtv9O3myMTE6+Pe0MrJ2dHQ4trXw8PD////wAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAAgALAAAAAAYABgAAARoEMlJq7046827/9ghjgd4FMZgGEUhlNwRAEEwqEMLZzLg2ypWS6Dp/WwsgpLAS/kAOeVqoNxVTjdogbAaUa0U7GprEE0O5VAhyAUjzJfTmODenFB00LmV17+3dR4HfX4ScIWIiYqLFBEAOw==";
